[package]
name = "MetaNote"
version = "0.0.2"
entrypoint = "metanote.typ"
authors = ["timetraveler314"]
license = "Unlicensed"
description = "MetaNote - A simple note templete for everyday mathematics"
